[package]
name = "web-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
reqwest = { version = "0.12.24", features = ["json", "multipart"] }
serde_json = "1.0"
core = { path = "../core" }
api-app = { path = "../api-app" }
