[package]
name = "api-graphql"
version = "0.1.0"
edition = "2024"

[dependencies]
kc-core = { path = "../kc-core" }
axum = "0.8.6"
serde = { version = "1.0.228", features = ["derive"] }
async-graphql = "7.0.17"
async-graphql-axum = "7.0.17"
