[server]
port = 8000
host = "0.0.0.0"
ipfs_host = "http://localhost:5001"
jwt_secret = "your_jwt_secret_key"

[node_health]
staleness_seconds = 90
check_interval_seconds = 60

[database]
connection = "postgres"
host = "postgres"
port = 5432
username = "keyston"
password = "keystonpassword"
database_name = "keyston_db"
pool_size = 5
